-- Create Projects tables for Suli Pool Admin
-- Run this in Supabase SQL Editor

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- Media Assets (only if you don't already have it)
-- ============================================
-- NOTE: Your app already references public.media_assets from other sections.
-- This is here to make the script self-contained on fresh projects.
CREATE TABLE IF NOT EXISTS public.media_assets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket text NOT NULL,
  path text NOT NULL,
  alt text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================
-- Projects (non-translated / shared fields)
-- ============================================

CREATE TABLE IF NOT EXISTS public.projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_enabled boolean NOT NULL DEFAULT true,
  -- Optional numeric value shown like "14 days" (can be NULL if you don't use it)
  duration_days integer NULL CHECK (duration_days IS NULL OR duration_days >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT projects_slug_unique UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS projects_sort_order_idx
  ON public.projects (sort_order);

CREATE INDEX IF NOT EXISTS projects_is_enabled_idx
  ON public.projects (is_enabled);

-- ============================================
-- Project Translations (localized text)
-- ============================================

CREATE TABLE IF NOT EXISTS public.project_translations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  locale text NOT NULL,
  -- e.g. "SIGNATURE" / "PERFORMANCE"
  badge text NOT NULL,
  title text NOT NULL,
  -- optional small line under title (if you need it later)
  subtitle text NULL,
  -- short excerpt on the card
  description text NULL,
  -- optional bottom meta like: ["Deck jets", "Hidden trough"] (language-specific)
  meta_items text[] NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_translations_unique_locale UNIQUE (project_id, locale)
);

CREATE INDEX IF NOT EXISTS project_translations_project_id_idx
  ON public.project_translations (project_id);

CREATE INDEX IF NOT EXISTS project_translations_locale_idx
  ON public.project_translations (locale);

-- ============================================
-- Project Images (one-to-many)
-- ============================================

CREATE TABLE IF NOT EXISTS public.project_images (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  media_id integer NOT NULL REFERENCES public.media_assets(id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  is_cover boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_images_unique_media_per_project UNIQUE (project_id, media_id)
);

CREATE INDEX IF NOT EXISTS project_images_project_id_idx
  ON public.project_images (project_id);

CREATE INDEX IF NOT EXISTS project_images_sort_order_idx
  ON public.project_images (sort_order);

-- Ensure at most 1 cover image per project
CREATE UNIQUE INDEX IF NOT EXISTS project_images_one_cover_per_project_idx
  ON public.project_images (project_id)
  WHERE is_cover = true;


